language: python
cache: pip
sudo: false

# Supported CPython versions:
# https://en.wikipedia.org/wiki/CPython#Version_history
matrix:
  fast_finish: true
  include:
    - python: 3.7
      dist: xenial
      sudo: required
    - python: 3.6
    - python: 3.5
    - python: 3.4
    - python: 2.7

install:
 - pip install -U pip
 - pip install -U pyflakes pycodestyle

script:
 # Static analysis
 - pyflakes .

after_script:
 # For info only, won't fail the build
 - pycodestyle --statistics --count .
